
	<a href="index.php" title="Accueil"> Accueil </a>
	<a href="histoire.php" title="Histoire"> Histoire </a>
	<a href="html.php" title="HTML"> HTML </a>
	<a href="css.php" title="CSS"> CSS </a>
	<a href="javascript.php" title="JavaScript"> JavaScript </a>
	<a href="outils.php" title="Outils"> Outils </a>
	<a href="contacts.php" title="Contacts"> Contacts </a>
	<a href="maPremierePagePHP.php" title="maPremierePagePHP"> PHP </a>
